// ============================================================
// SALES & REVENUE MEASURES
// Enterprise Sales Analytics - DAX Measure Library
// ============================================================

// --- Core Revenue Metrics ---

Total Revenue = 
SUMX(
    fact_sales,
    fact_sales[quantity] * fact_sales[unit_price] * (1 - fact_sales[discount_pct])
)

Total Cost = 
SUMX(
    fact_sales,
    fact_sales[quantity] * RELATED(dim_products[unit_cost])
)

Gross Profit = [Total Revenue] - [Total Cost]

Gross Margin % = 
DIVIDE([Gross Profit], [Total Revenue], 0)

Total Orders = DISTINCTCOUNT(fact_sales[order_id])

Total Quantity Sold = SUM(fact_sales[quantity])

Average Order Value = 
DIVIDE([Total Revenue], [Total Orders], 0)

// --- Time Intelligence Measures ---

Revenue YTD = 
TOTALYTD([Total Revenue], dim_date[full_date])

Revenue QTD = 
TOTALQTD([Total Revenue], dim_date[full_date])

Revenue MTD = 
TOTALMTD([Total Revenue], dim_date[full_date])

Revenue Previous Year = 
CALCULATE(
    [Total Revenue],
    SAMEPERIODLASTYEAR(dim_date[full_date])
)

Revenue YoY Growth = 
VAR CurrentYear = [Total Revenue]
VAR PreviousYear = [Revenue Previous Year]
RETURN
DIVIDE(CurrentYear - PreviousYear, PreviousYear, 0)

Revenue YoY Growth % = 
FORMAT([Revenue YoY Growth], "0.0%")

Revenue Previous Month = 
CALCULATE(
    [Total Revenue],
    DATEADD(dim_date[full_date], -1, MONTH)
)

Revenue MoM Growth % = 
VAR CurrentMonth = [Total Revenue]
VAR PreviousMonth = [Revenue Previous Month]
RETURN
DIVIDE(CurrentMonth - PreviousMonth, PreviousMonth, 0)

Revenue Rolling 3M = 
CALCULATE(
    [Total Revenue],
    DATESINPERIOD(dim_date[full_date], MAX(dim_date[full_date]), -3, MONTH)
)

Revenue Rolling 12M = 
CALCULATE(
    [Total Revenue],
    DATESINPERIOD(dim_date[full_date], MAX(dim_date[full_date]), -12, MONTH)
)

// --- Moving Averages ---

Revenue 7Day Moving Avg = 
AVERAGEX(
    DATESINPERIOD(dim_date[full_date], MAX(dim_date[full_date]), -7, DAY),
    [Total Revenue]
)

Revenue 30Day Moving Avg = 
AVERAGEX(
    DATESINPERIOD(dim_date[full_date], MAX(dim_date[full_date]), -30, DAY),
    [Total Revenue]
)

// --- Target & KPI Measures ---

Target Revenue = 
SUM(fact_targets[target_revenue])

Revenue vs Target = 
[Total Revenue] - [Target Revenue]

Revenue vs Target % = 
DIVIDE([Total Revenue], [Target Revenue], 0) - 1

Target Achievement Rate = 
DIVIDE([Total Revenue], [Target Revenue], 0)

Target Achievement Indicator = 
SWITCH(
    TRUE(),
    [Target Achievement Rate] >= 1.1, "★★★ Exceeding",
    [Target Achievement Rate] >= 1.0, "★★ On Target",
    [Target Achievement Rate] >= 0.85, "★ Below Target",
    "⚠ Critical"
)

// --- Customer Analytics ---

Total Customers = DISTINCTCOUNT(fact_sales[customer_id])

New Customers = 
VAR CurrentPeriodEnd = MAX(dim_date[full_date])
VAR CurrentPeriodStart = MIN(dim_date[full_date])
RETURN
COUNTROWS(
    FILTER(
        VALUES(fact_sales[customer_id]),
        CALCULATE(
            MIN(fact_sales[order_date]),
            ALL(dim_date)
        ) >= CurrentPeriodStart
        && CALCULATE(
            MIN(fact_sales[order_date]),
            ALL(dim_date)
        ) <= CurrentPeriodEnd
    )
)

Revenue Per Customer = 
DIVIDE([Total Revenue], [Total Customers], 0)

Customer Lifetime Value = 
AVERAGEX(
    VALUES(dim_customers[customer_id]),
    CALCULATE([Total Revenue])
)

// --- Product Analytics ---

Top Product Revenue = 
MAXX(
    VALUES(dim_products[product_name]),
    CALCULATE([Total Revenue])
)

Product Rank by Revenue = 
RANKX(
    ALL(dim_products[product_name]),
    CALCULATE([Total Revenue]),
    ,
    DESC,
    DENSE
)

Category Contribution % = 
DIVIDE(
    [Total Revenue],
    CALCULATE([Total Revenue], ALL(dim_products[category])),
    0
)

// --- Returns & Quality ---

Total Returns = COUNTROWS(fact_returns)

Return Rate % = 
DIVIDE(
    COUNTROWS(fact_returns),
    [Total Orders],
    0
)

Total Refund Amount = SUM(fact_returns[refund_amount])

Net Revenue = [Total Revenue] - [Total Refund Amount]

// --- Discount Analysis ---

Average Discount = AVERAGE(fact_sales[discount_pct])

Revenue Without Discount = 
SUMX(
    fact_sales,
    fact_sales[quantity] * fact_sales[unit_price]
)

Discount Impact = 
[Revenue Without Discount] - [Total Revenue]

// --- Channel Performance ---

Channel Contribution % = 
DIVIDE(
    [Total Revenue],
    CALCULATE([Total Revenue], ALL(fact_sales[channel])),
    0
)

// --- Dynamic Measures for Drill-Through ---

Selected Period Label = 
VAR MinDate = MIN(dim_date[full_date])
VAR MaxDate = MAX(dim_date[full_date])
RETURN
FORMAT(MinDate, "MMM DD, YYYY") & " - " & FORMAT(MaxDate, "MMM DD, YYYY")

Selected Region = 
IF(
    HASONEVALUE(dim_customers[region]),
    VALUES(dim_customers[region]),
    "All Regions"
)

// --- Conditional Formatting Helpers ---

Revenue Trend Color = 
IF([Revenue YoY Growth] > 0, "#2ECC71", "#E74C3C")

Margin Status Color = 
SWITCH(
    TRUE(),
    [Gross Margin %] >= 0.4, "#2ECC71",
    [Gross Margin %] >= 0.25, "#F39C12",
    "#E74C3C"
)
